"use client";
import type { KeyboardEvent } from "react";
import { Glyph, dateText, itemStamp, itemText, money, phase, plural } from "./AdminBits";
import type { Checklist, Data, Item, Need, Progress } from "./adminTypes";
import s from "./adminPanels.module.css";

type Props={data:Data|null;checklist:Checklist|null;selected:string;busy:boolean;onSelect:(id:string)=>void;onNeed:(n:Need)=>void;onOpen:(mode:"client"|"project"|"time",project?:string)=>void;onChecklist:(i:Item,a:"accept"|"nudge"|"not_applicable"|"restore")=>void;onChanges:(i:Item)=>void;onRemove:(i:Item)=>void;onAddItem:(project:string)=>void;onCheckin:(p:NonNullable<Progress>)=>void};

export default function AdminMain({data,checklist,selected,busy,onSelect,onNeed,onOpen,onChecklist,onChanges,onRemove,onAddItem,onCheckin}:Props){
 const progress=data?.checkinProgress;
 function rowKey(e:KeyboardEvent<HTMLTableRowElement>,id:string){if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(id)}}
 return <section className={s.main}>
  <header className={s.pageHead}><div><p className={s.eyebrow}>Welcome back, Kyle.</p><h1>Needs you</h1><p>A few things need your attention to keep projects moving.</p></div><div><time>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric",year:"numeric"}).format(new Date())}</time><em>“Steady progress compounds.”</em></div></header>
  <section className={s.needs} id="needs-you" aria-labelledby="needs-title"><h2 id="needs-title" className={s.sr}>Needs you</h2>{data?.needs.length?data.needs.map(n=><article key={n.id}><span className={s.needIcon}><Glyph name={n.kind==="invoice"?"money":n.kind==="time_checkin"?"time":n.kind==="onboarding"?"files":"messages"}/></span><div><strong>{n.title}</strong><small>{n.evidence}</small></div><button type="button" disabled={busy} onClick={()=>onNeed(n)}>{n.actionLabel}</button></article>):<div className={s.clearState}><span>Nothing needs you right now.</span><i/><small>Everything that can move is moving.</small></div>}</section>
  <section className={s.metrics} aria-label="Portal metrics"><div><Glyph name="folder"/><span><small>Active projects</small><b>{plural(data?.metrics.activeProjects||0,"project")}</b></span></div><div><Glyph name="time"/><span><small>Hours this month</small><b>{(data?.metrics.hoursThisMonth||0).toFixed(1)} hours</b></span></div><div><Glyph name="money"/><span><small>Outstanding</small><b>{money(data?.metrics.outstanding||0)}</b></span></div><div><Glyph name="people"/><span><small>Awaiting client response</small><b>{plural(data?.metrics.awaitingClientItems||0,"item")}</b></span></div></section>
  <section className={s.panel} id="projects"><div className={s.panelTitle}><h2>Active projects</h2><button type="button" onClick={()=>onOpen("project")}>+ Project</button></div>{data?.projects.length?<div className={s.tableWrap}><table><thead><tr><th>Client</th><th>Project</th><th>Phase</th><th>Onboarding %</th><th>Hours logged</th><th>Amount due</th><th>Last activity</th><th><span className={s.sr}>Open</span></th></tr></thead><tbody>{data.projects.map(x=><tr key={x.id} tabIndex={0} onClick={()=>onSelect(x.id)} onKeyDown={e=>rowKey(e,x.id)}><td>{x.clientName}</td><td>{x.name}</td><td><span className={`${s.phase} ${s[`phase_${x.phase}`]||""}`}><i/>{phase(x.phase)}</span></td><td><span className={s.miniProgress}><i><span style={{width:`${x.onboardingPercent}%`}}/></i><b>{x.onboardingPercent}%</b></span></td><td>{x.hoursLogged.toFixed(1)} hrs</td><td>{money(x.amountDue)}</td><td>{dateText(x.lastActivity)}</td><td><Glyph name="open"/></td></tr>)}</tbody></table></div>:<Empty title="No active projects yet." body="Add a client and their first project will appear here with a cloned onboarding checklist." action="Add first client" onClick={()=>onOpen("client")}/>}</section>
  <section className={`${s.panel} ${s.onboarding}`} id="onboarding"><div className={s.onboardHead}><div><h2>Onboarding checklist{checklist?` — ${checklist.clientName}`:""}</h2>{data?.checklists.length?<div className={s.tabs} role="tablist" aria-label="Checklist project">{data.checklists.map(c=><button type="button" role="tab" aria-selected={c.projectId===selected} className={c.projectId===selected?s.tabActive:""} key={c.projectId} onClick={()=>onSelect(c.projectId)}>{c.clientName}</button>)}</div>:null}</div>{checklist?<div className={s.onboardProgress}><span>{checklist.complete} of {checklist.total} complete</span><i><b style={{width:`${checklist.percent}%`}}/></i><strong>{checklist.percent}%</strong></div>:null}</div>{checklist?<><div className={s.items}>{checklist.items.map(i=><article key={i.id} className={`${s.item} ${s[`item_${i.status}`]}`}><span className={s.itemIcon}><Glyph name={i.status==="accepted"?"check":i.status==="needs_changes"?"warn":i.status==="submitted"?"review":"pending"}/></span><div className={s.itemName}><strong>{i.name}</strong><small>{i.itemType}</small></div><span className={s.itemStatus}>{itemText(i)}</span><time>{itemStamp(i)}</time><div className={s.itemActions}>{i.status==="pending"?<button type="button" onClick={()=>onChecklist(i,"nudge")}>Nudge</button>:null}{i.status==="submitted"||i.status==="needs_changes"?<><button type="button" onClick={()=>onChecklist(i,"accept")}>Accept</button><button type="button" onClick={()=>onChanges(i)}>Request changes</button></>:null}{i.status==="accepted"?<button disabled>✓ Accepted</button>:null}{i.status==="not_applicable"?<button type="button" onClick={()=>onChecklist(i,"restore")}>Restore</button>:<button className={s.mutedAction} type="button" onClick={()=>onChecklist(i,"not_applicable")}>N/A</button>}<button className={s.menuBtn} type="button" aria-label={`Remove ${i.name}`} onClick={()=>onRemove(i)}><Glyph name="menu"/></button></div></article>)}</div><button className={s.addItem} type="button" onClick={()=>onAddItem(checklist.projectId)}>+ Add checklist item</button></>:<Empty title="No checklist to review yet." body="Create an active project and the eight-item template is cloned automatically." action="Create project" onClick={()=>onOpen("project")}/>}</section>
  <section className={`${s.panel} ${s.timePanel}`} id="time-log"><div className={s.timeHead}><div><h2>Time log</h2><p>Recent time entries across all projects.</p></div>{progress?<div className={s.checkin}><span>{progress.clientName} — {progress.sinceLastCheckin.toFixed(1)} of 10 hours</span><i><b style={{width:`${progress.percent}%`}}/></i><strong>{progress.percent}%</strong>{progress.due?<button type="button" onClick={()=>onCheckin(progress)}>Mark check-in sent</button>:null}</div>:null}<button type="button" onClick={()=>onOpen("time")}>Log time</button></div><div className={s.timeBody}>{data?.recentTimeEntries.length?<div className={s.tableWrap}><table><thead><tr><th>Date</th><th>Client</th><th>Phase</th><th>Description</th><th>Hours</th></tr></thead><tbody>{data.recentTimeEntries.slice(0,6).map(x=><tr key={x.id}><td>{dateText(x.date)}</td><td>{x.clientName}</td><td>{x.phase}</td><td>{x.description}</td><td>{x.hours.toFixed(1)} hrs</td></tr>)}</tbody></table></div>:<Empty title="No time logged yet." body="Start the clock on a project and your 10-hour check-in progress begins here." action="Log first entry" onClick={()=>onOpen("time")}/>}<aside className={s.archiveEmpty}><Glyph name="time"/><span>No archived weekly recaps yet.</span><p>Closed-week summaries will collect here as your work history grows.</p><button type="button" onClick={()=>onOpen("time")}>Log time</button></aside></div></section>
 </section>
}
function Empty({title,body,action,onClick}:{title:string;body:string;action:string;onClick:()=>void}){return <div className={s.empty}><span>{title}</span><p>{body}</p><button type="button" onClick={onClick}>{action}</button></div>}
